name: UseCaseToTestCase
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  libtcc:
    path: ../libtcc
  shelf: any
  shelf_cors: any
  shelf_route: any
  logging : any
dev_dependencies:
  unittest: any
